### PR TITLE
Markdown formatting fixes.

### PR DESCRIPTION
**Pull request by postmodern**
Formatting fixes for the README.

### CODE REVIEW

**Comment by jaredonline** [comment]
+1 Way easier to read.

**Comment by bearded** [comment]
@RobertFischer, come on, just click to Merge button, README will be much more [readable](https://github.com/RobertFischer/JQuery-PeriodicalUpdater/blob/ef74f7acf7211afd4b4f662ee29789029aede154/README.md)

**Comment by RobertFischer** [comment]
This isn't a fast-forward merge, and postmodern doesn't have a GitHub repo for this project yet. How do I pull the change down into my local repo to apply the merge?

**Comment by RobertFischer** [comment]
Applied it manually in ref a1b9343 — let me know if I missed anything.

**Comment by bearded** [comment]
Github guide about [Remotes](http://help.github.com/remotes/) should help

**Comment by bearded** [comment]
Thank you! :)

**Comment by RobertFischer** [comment]
I understand how remotes work. Where's the ref for this patch live? When I try to fetch it from origin, it says the ref doesn't exist.

**Comment by bearded** [comment]
I think problem is that @postmodern already [removed his fork](https://github.com/postmodern/JQuery-PeriodicalUpdater).
Please try to merge #15, @alexdean has not removed his [fork](https://github.com/alexdean/JQuery-PeriodicalUpdater).

**Comment by bearded** [comment]
@RobertFischer, I sent [PR](https://github.com/alexdean/JQuery-PeriodicalUpdater/pull/2) to @alexdean to help you merge #15 (along with my fixes for Lint warnings) :)

I would also help you to merge #21 (**verbose** option is really nice idea) and #14 (added support for **jsonp requests**, that is really important)

**Comment by alexdean** [comment]
@bearded: Done. Hope that helps!

**Comment by bearded** [comment]
@alexdean, thx a lot! :)

**Pull request closed without merging**
